import { defineObject, FieldType, OnDeleteAction, RelationType } from 'twenty-sdk/define';

import {
  DOCUMENT_TEMPLATE_FIELDS,
  DOCUMENT_TEMPLATE_OBJECT_UNIVERSAL_IDENTIFIER,
  GENERATED_DOCUMENT_FIELDS,
  GENERATED_DOCUMENT_OBJECT_UNIVERSAL_IDENTIFIER,
} from '../constants/model-identifiers';

enum GeneratedDocumentStatus {
  RENDERED = 'RENDERED',
  PDF_GENERATED = 'PDF_GENERATED',
  FAILED = 'FAILED',
}

export default defineObject({
  universalIdentifier: GENERATED_DOCUMENT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'generatedDocument',
  namePlural: 'generatedDocuments',
  labelSingular: 'GeneratedDocument',
  labelPlural: 'Generated Documents',
  description: 'Audit record for a document rendered from CRM data.',
  icon: 'IconFileText',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: GENERATED_DOCUMENT_FIELDS.name,
  fields: [
    { universalIdentifier: GENERATED_DOCUMENT_FIELDS.name, type: FieldType.TEXT, name: 'name', label: 'Name', description: 'Generated document name', icon: 'IconAbc' },
    {
      universalIdentifier: GENERATED_DOCUMENT_FIELDS.template,
      type: FieldType.RELATION,
      name: 'template',
      label: 'DocumentTemplate',
      description: 'Template used for generation',
      icon: 'IconTemplate',
      relationTargetFieldMetadataUniversalIdentifier: DOCUMENT_TEMPLATE_FIELDS.generatedDocuments,
      relationTargetObjectMetadataUniversalIdentifier: DOCUMENT_TEMPLATE_OBJECT_UNIVERSAL_IDENTIFIER,
      universalSettings: { relationType: RelationType.MANY_TO_ONE, onDelete: OnDeleteAction.SET_NULL, joinColumnName: 'templateId' },
      isNullable: true,
    },
    { universalIdentifier: GENERATED_DOCUMENT_FIELDS.primaryObjectType, type: FieldType.TEXT, name: 'primaryObjectType', label: 'Primary Object Type', description: 'Source object type such as company or person', icon: 'IconDatabase', isNullable: true, defaultValue: null },
    { universalIdentifier: GENERATED_DOCUMENT_FIELDS.primaryRecordId, type: FieldType.TEXT, name: 'primaryRecordId', label: 'Primary Record ID', description: 'Source record identifier', icon: 'IconId', isNullable: true, defaultValue: null },
    { universalIdentifier: GENERATED_DOCUMENT_FIELDS.renderedHtml, type: FieldType.RICH_TEXT, name: 'renderedHtml', label: 'Rendered HTML', description: 'Rendered HTML snapshot', icon: 'IconCode', isNullable: true, defaultValue: null },
    { universalIdentifier: GENERATED_DOCUMENT_FIELDS.pdfUrl, type: FieldType.TEXT, name: 'pdfUrl', label: 'PDF URL', description: 'Stored PDF URL', icon: 'IconFileTypePdf', isNullable: true, defaultValue: null },
    {
      universalIdentifier: GENERATED_DOCUMENT_FIELDS.status,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Generation lifecycle state',
      icon: 'IconStatusChange',
      defaultValue: `'${GeneratedDocumentStatus.RENDERED}'`,
      options: [
        { value: GeneratedDocumentStatus.RENDERED, label: 'Rendered', position: 0, color: 'blue' },
        { value: GeneratedDocumentStatus.PDF_GENERATED, label: 'PDF Generated', position: 1, color: 'green' },
        { value: GeneratedDocumentStatus.FAILED, label: 'Failed', position: 3, color: 'red' },
      ],
    },
    { universalIdentifier: GENERATED_DOCUMENT_FIELDS.errorMessage, type: FieldType.RICH_TEXT, name: 'errorMessage', label: 'Error Message', description: 'Failure reason', icon: 'IconAlertTriangle', isNullable: true, defaultValue: null },
    { universalIdentifier: GENERATED_DOCUMENT_FIELDS.generatedBy, type: FieldType.TEXT, name: 'generatedBy', label: 'Generated By', description: 'User id or display name that generated it', icon: 'IconUser', isNullable: true, defaultValue: null },
    { universalIdentifier: GENERATED_DOCUMENT_FIELDS.generatedAt, type: FieldType.DATE_TIME, name: 'generatedAt', label: 'Generated At', description: 'Generation timestamp', icon: 'IconCalendarTime', isNullable: true, defaultValue: null },
    { universalIdentifier: GENERATED_DOCUMENT_FIELDS.metadata, type: FieldType.RAW_JSON, name: 'metadata', label: 'Metadata', description: 'Audit metadata and warnings', icon: 'IconJson', isNullable: true, defaultValue: null },
  ],
});
